# Hugging Face Veri Seti Kalite Analizi

## tl;dr

- **45 veri setinde 87,831 satır** yerel sabit
  kopyalardan profillendi.
- Şema dağılımı: **catalog: 1, conversation: 43, tabular: 1**. Sohbet veya düz istem–cevap
  biçimindeki toplam kayıt sayısı **87,228**.
- Ayrı `thinking` içeren kayıt sayısı **67,470**; metin
  biçiminde saklanan `null` alan sayısı **462**.
- Erişim engeli nedeniyle analiz edilemeyen veri seti sayısı
  **2**; bunlar sessizce atlanmadı, kanıtlarıyla
  birlikte ayrı bir tabloda listeleniyor.
- Tekrar, eksik değer, metin uzunluğu ve zaman hassasiyeti ölçümleri
  kullanım amacına göre yorumlanmalı; satır hacmi tek başına kalite
  göstergesi değildir.

## Bağlam ve Yöntem

Analiz, Hugging Face Dataset Viewer üzerinden indirilen tam yerel
kopyalar ve sabit kaynak revizyonları üzerinde çalışır. Kontroller;
şema, tamamlılık, rol sırası, birebir ve normalleştirilmiş tekrar,
metin uzunluğu, `thinking`, metin biçimindeki `null`, kişisel veri
biçimleri ve zaman hassasiyeti sinyallerini kapsar.

### Temel Varsayımlar

- Normalleştirilmiş tekrar oranı, her metin ailesindeki ilk örnekten
  sonraki ek kopyaların tüm satırlara bölünmesiyle hesaplanır.
- Zaman hassasiyeti sayıları regex eşleşmeleridir; benzersiz satır
  sayısı değildir.
- Regex taraması bağlamsal kişi ve kurum adlarını bütünüyle yakalayamaz.
- Yapısal doğrulama, her cevabın alan uzmanı tarafından olgusal olarak
  onaylandığı anlamına gelmez.

## Veri

In [1]:
import json
from pathlib import Path
import pandas as pd

WORKING_DIR = Path.cwd()
PROJECT_DIR = next(
    (
        candidate
        for candidate in (WORKING_DIR, WORKING_DIR.parent)
        if (candidate / "outputs" / "data_quality_profiles.json").exists()
    ),
    None,
)
if PROJECT_DIR is None:
    raise FileNotFoundError(
        "Project outputs were not found in the working directory or its parent."
    )

profiles = json.loads(
    (PROJECT_DIR / "outputs" / "data_quality_profiles.json").read_text(encoding="utf-8")
)
overlaps = json.loads(
    (PROJECT_DIR / "outputs" / "cross_dataset_overlap.json").read_text(encoding="utf-8")
)
manual_path = PROJECT_DIR / "outputs" / "manual_findings.json"
manual = json.loads(manual_path.read_text(encoding="utf-8")) if manual_path.exists() else {"datasets": {}}
excluded = json.loads(
    (PROJECT_DIR / "outputs" / "excluded_datasets.json").read_text(encoding="utf-8")
)["datasets"]

len(profiles), sum(item["profile"]["row_count"] for item in profiles)

(45, 87831)

### Analiz edilemeyen veri setleri

Kayıt defterinde etkin olduğu hâlde erişilemeyen veri setleri kapsam
dışı bırakılmaz; her biri canlı olarak yeniden doğrulanmış HTTP
kanıtıyla birlikte burada listelenir. Aşağıdaki satırlar toplam satır
sayısına dâhil değildir.

In [2]:
pd.DataFrame([
    {
        "dataset": item["dataset_id"],
        "contributor": item.get("contributor"),
        "status": item["status"],
        "reverified_on": item.get("reverified_on"),
        "http_status": ", ".join(
            str(check.get("status")) for check in item.get("reverified_checks", [])
        ),
    }
    for item in excluded
])

,dataset,contributor,status,reverified_on,http_status
0,menesnas/Pharmacy_Identity_Synthetic_QA,Muhammet Enes Nas,gated_manual,2026-07-22,"200, 404"
1,uzcaliskan/magibu_dataset_drilling,Oguz Caliskan,not_found_or_private,2026-07-22,"404, 404"

In [3]:
summary_rows = []
for item in profiles:
    profile = item["profile"]
    scan = profile.get("text_scan", {})
    summary_rows.append({
        "dataset": item["dataset_id"],
        "contributor": item.get("contributor"),
        "rows": profile["row_count"],
        "shape": profile["data_shape"],
        "exact_duplicates": profile.get("exact_duplicate_rows", 0),
        "prompt_duplicates_%": round(100 * profile.get("user_prompt_duplicates", {}).get("duplicate_rate", 0), 2),
        "answer_duplicates_%": round(100 * profile.get("assistant_answer_duplicates", {}).get("duplicate_rate", 0), 2),
        "thinking": profile.get("nonempty_thinking_messages", 0),
        "string_nulls": profile.get("string_encoded_null_fields", 0),
        "time_sensitive_matches": scan.get("time_sensitive_matches", 0),
        "answer_words_median": profile.get("assistant_word_length", {}).get("median"),
        "answer_words_p95": profile.get("assistant_word_length", {}).get("p95"),
        "near_dup_answers_%": round(100 * (profile.get("assistant_answer_near_duplicates", {}).get("near_duplicate_rate") or 0), 2),
        "distinct_answers": profile.get("assistant_answer_duplicates", {}).get("distinct_values"),
        "distinct_rows": profile.get("distinct_canonical_rows"),
        "language_signal": profile.get("text_scan", {}).get("dominant_language_signal"),
        "topic_concentration_%": round(100 * ((profile.get("topic_profile") or {}).get("topic_concentration") or 0), 1),
        "distinctive_terms": ", ".join(
            t["term"] for t in (profile.get("topic_profile") or {}).get("distinctive_terms", [])[:5]
        ),
        "json_answers": profile.get("structured_answers", {}).get("json_parsable_answers", 0),
        "json_like_broken": profile.get("structured_answers", {}).get("json_like_but_unparsable_answers", 0),
        "conflicting_prompt_families": profile.get("answer_families", {}).get(
            "prompt_families_with_conflicting_answers", 0
        ),
        "cross_split_duplicate_rows": profile.get("split_integrity", {}).get(
            "cross_split_duplicate_rows", 0
        ),
    })

summary = pd.DataFrame(summary_rows).sort_values("dataset").reset_index(drop=True)
summary

,dataset,contributor,rows,shape,exact_duplicates,prompt_duplicates_%,answer_duplicates_%,thinking,string_nulls,time_sensitive_matches,...,near_dup_answers_%,distinct_answers,distinct_rows,language_signal,topic_concentration_%,distinctive_terms,json_answers,json_like_broken,conflicting_prompt_families,cross_split_duplicate_rows
0,Aysenur44/namaz-vakti-dua-asistan-tr,Ayşe Nur Yeşilova,60,conversation,0,0.00,0.00,0,0,0,...,6.67,60.0,60,turkish,58.9,"namazı, hocam, detaylı, kılınabilir, vakti",0,0,0,0
1,Aysenur44/namaz-vakti-identity-tr,Ayşe Nur Yeşilova,4,conversation,0,0.00,0.00,0,0,0,...,0.00,4.0,4,turkish,100.0,"yararsın, adın, kimsin, seni, geliştirdi",0,0,0,0
2,Egertekin/marvel-domain-dataset,Ege Ertekin,177,conversation,0,75.71,13.56,0,0,1,...,13.56,153.0,177,turkish,80.6,"örümcek, spider, adam, detaylı, marvel",0,0,7,0
3,Endezyar/siyer_datasets,Muhammed Bakır Kurt,509,conversation,0,0.98,0.39,0,0,0,...,0.39,507.0,509,turkish,24.1,"efendimiz, müslüman, peygamberimiz, kabile, hi...",0,0,3,0
4,Erenyanic/seasoned-advice-dataset,Eren Yanic,1000,conversation,0,0.00,0.00,1000,0,28,...,0.00,1000.0,1000,turkish,7.0,"cooking, water, pişirme, some, recipe",0,24,0,0
5,Mer1Alii/TR-ECommerce-CustomerSupport-Instruct...,Mert Ali Alkan,186,conversation,0,0.00,0.00,186,0,31,...,0.00,186.0,186,turkish,15.3,"sipariş, kargo, fatura, iade, iptal",0,0,0,0
6,SalihHub/trendyol-marangoz-urun-asistan-qa,Salih Dede,1211,conversation,0,1.32,15.11,1211,0,10,...,9.41,1028.0,1211,turkish,22.5,"merhaba, acaba, ürün, ürünün, duvara",0,0,12,0
7,Talayhan/skatepal_dataset,Talayhan,299,conversation,0,0.00,0.00,299,0,26,...,0.00,299.0,299,turkish,11.9,"kaykay, skateboard, skate, board, kickflip",0,0,0,0
8,Toivo0/Turkce-istatistik-reasoning,Umut Kıvanç Sipahioglu,400,conversation,0,0.00,0.00,400,0,12,...,0.00,400.0,400,turkish,16.3,"dağılımı, istatistiksel, olasılık, değişken, ö...",0,0,0,0
9,Uunan/turkish-cuisine-qa,Uunan,34244,conversation,0,0.01,0.05,34244,0,0,...,1.46,34227.0,34244,turkish,31.8,"tarifinde, aittir, çorbası, yapım, öğün",0,0,2,0
10,YusufSimsek/llm-kisisellestirme,Yusuf Şimşek,46,conversation,0,0.00,0.00,0,0,0,...,0.00,46.0,46,turkish,53.5,"yusuf, birisi, ilgileniyor, senden, projeleri",0,0,0,0
11,YusufSimsek/turkce-atasozleri-dataset,Yusuf Şimşek,1398,conversation,0,0.21,68.10,1398,0,0,...,67.95,446.0,1398,turkish,35.6,"atasözü, anlatmaktadır, anlamı, sanır, allah",0,0,3,0
12,aliFurkan123/cultural-questions-dataset,Ali Furkan Ak,500,conversation,0,0.00,0.00,500,0,4,...,0.40,500.0,500,turkish,52.3,"katının, başkenti, soracağım, kafadan, arkadaşlar",0,0,0,0
13,aliFurkan123/identity,Ali Furkan Ak,30,conversation,0,0.00,36.36,33,0,0,...,46.67,21.0,30,english,75.5,"furkan, trained, tuned, goal, fine",0,0,0,0
14,berkbirkan/turkish-x-engagement-quotes,Berk Birkan,1000,conversation,0,67.70,0.00,0,0,141,...,0.00,1000.0,1000,turkish,29.1,"içgörü, quote, özgün, alıntılarken, ekleyen",0,0,229,0
15,berkbirkan/turkish-x-engagement-replies,Berk Birkan,1000,conversation,0,70.10,0.00,0,0,120,...,0.10,1000.0,1000,turkish,25.3,"reply, aşağıdaki, doğal, bağlama, gönderisine",0,0,212,0
16,berkcangumusisik/voleykoc-antrenorluk-tr,Berkcan Gümüşışık,166,conversation,0,0.00,24.70,0,0,66,...,25.90,125.0,166,turkish,48.6,"voleybol, takımı, kadın, devamı, sormamı",0,0,0,0
17,berkcangumusisik/voleykoc-identity-tr,Berkcan Gümüşışık,182,conversation,0,0.00,85.71,0,0,0,...,85.71,26.0,182,turkish,46.8,"pardon, soracağım, sorry, selam, curious",0,0,0,0
18,cihatyldz/lojistik-soru-cevap,Cihat Yıldız,139,conversation,0,0.00,0.00,0,0,1,...,0.00,139.0,139,turkish,35.9,"lojistik, taşımacılığı, kargo, kurye, teslimat",0,0,0,0
19,enes1863/bilisim-hukuku-domain-dataset,Enes Hakan,1000,conversation,0,0.00,98.00,1000,0,0,...,98.00,20.0,1000,turkish,33.4,"veri, kişisel, anonim, hâle, rıza",0,0,0,0
20,enesozdemr/benim_ilk_datasetim,enesozdemr,113,conversation,0,0.00,84.96,113,0,0,...,84.96,17.0,113,turkish,96.3,"kokulandırılır, petrol, boru, hattı, doğal",0,0,0,0
21,erhanalsr/langusta-identity,Erhan Alasar,100,conversation,0,0.00,80.00,0,0,0,...,76.00,20.0,100,turkish,56.3,"yanıtla, cümleyle, açıkça, soruyu, cevapla",0,0,0,0
22,erhanalsr/langusta-kpss-reasoning,Erhan Alasar,21,conversation,0,0.00,0.00,21,0,0,...,0.00,21.0,21,turkish,27.4,"aşağıdakilerden, seçenekler, medresesi, şarkıs...",0,0,0,0
23,filiz-yalcin/identity-finetune,Filiz Yalçin,1600,conversation,0,2.62,0.31,1600,0,1038,...,0.63,1593.0,1600,turkish,24.6,"misiniz, function, zeka, creation, model",0,0,33,0
24,filiz-yalcin/turkish-figure-skating-qa,Filiz Yalçin,526,conversation,0,1.90,0.76,526,0,47,...,1.90,522.0,526,turkish,44.8,"pateninde, artistik, yarışmalarında, atlayış, ...",0,0,8,0
25,gmz1234/stackoverflow_ai,gmz1234,1000,conversation,0,0.00,0.00,0,0,0,...,0.00,1000.0,1000,english,12.0,"neural, network, learning, action, function",0,2,0,0
26,gorkemergune/ayarlicazhocam_finetune,Görkem Ergüne,429,conversation,4,10.72,0.93,429,0,30,...,2.10,425.0,425,turkish,26.2,"project, gorkem, onerir, görkem, projesi",0,0,34,0
27,gururaser/ithaki-bilimkurgu-klasikleri,Gurur Aşer,103,catalog,0,0.00,0.00,0,0,0,...,0.00,NaN,103,turkish,26.3,"bilimkurgu, thaki, klasikleri, yayınları, mars",0,0,0,0
28,haticenurcakr/turkish-classic-books-qa,Hatice Nur Çakır,220,conversation,0,0.00,1.82,0,0,0,...,1.82,216.0,220,turkish,62.8,"eserinin, yayımlanmıştır, edebiyatında, yazarı...",0,0,0,0
29,meldakahramann/animasyon-domain-dataset,Melda Kahraman,1020,conversation,0,0.00,58.82,1020,0,0,...,61.86,420.0,1020,turkish,43.0,"filminin, animasyonu, seslendirenleri, filmi, ...",0,0,0,0
30,namruni/meb-ogretmen-soru-cevap,Mustafa Özdemir,450,conversation,0,0.00,0.00,450,0,297,...,0.00,450.0,450,turkish,12.3,"öğretmen, tayin, tayini, arkadaşlar, norm",0,0,0,0
31,nursimakgul/meb-soru-uretme,Nur Sima Akgül,20874,conversation,178,86.63,1.27,20874,0,560,...,2.68,20609.0,20696,turkish,73.5,"üret, çoktan, sınıf, seçmeli, orta",17454,0,797,0
32,nyzmemre/biyoloji-terimleri-turkce-sa,Mehmet Emre Öz,1093,conversation,0,0.18,21.59,0,0,0,...,22.32,857.0,1093,turkish,38.4,"teriminin, ders, kitaplarında, tanım, açıklama",0,0,2,0
33,sadecebirisii/turkish-llm-authority-bypass-saf...,Hilal Kavas,29,conversation,0,0.00,0.00,0,0,8,...,0.00,29.0,29,turkish,14.6,"adim, icin, anthropic, saldirisi, safety",0,0,0,0
34,samliumay/turkish_cyber_security_controls_dataset,Umay Şamlı,800,conversation,0,0.00,0.00,0,0,38,...,0.00,800.0,800,turkish,19.7,"güvenlik, bulut, erişim, kontrol, veri",0,0,0,0
35,samliumay/umay_samli_identification_dataset,Umay Şamlı,219,conversation,0,0.00,66.67,0,0,62,...,66.67,73.0,219,turkish,40.4,"umay, yaratıcının, nato, güvenlik, sertifikası",0,0,0,0
36,seali/turkce-saglik-qa,Seyit Ali Yorğun,773,conversation,0,0.13,0.00,773,0,16,...,0.00,773.0,773,turkish,48.9,"diyabetli, ergenlerde, bilmem, obezite, konusunda",0,0,1,0
37,sedayzc/trendyol-electronics-products-features...,Seda Nur Yazıcı,500,tabular,0,0.00,0.00,0,0,398,...,0.00,NaN,500,turkish,22.5,"gayet, ürün, teşekkür, güzel, ederim",0,0,0,0
38,sedayzc/turkish-electronics-product-comparison...,Seda Nur Yazıcı,11858,conversation,4851,41.37,52.25,0,0,699,...,55.96,5662.0,7007,turkish,38.1,"16gb, 512gb, core, intel, ryzen",0,0,55,0
39,senemde/saglik-qa-tr,Senem Deniz,553,conversation,0,0.00,0.54,0,0,2,...,1.08,550.0,553,turkish,18.3,"diyabetin, hastalarında, diabetes, glukoz, ges...",0,1,0,0
40,sk75/sahin_identity,Serhat Kılıç,77,conversation,0,0.00,64.94,0,462,0,...,64.94,27.0,77,turkish,29.6,"arkanda, model, seni, built, team",0,0,0,0
41,srhskrkc/odysseia-destani-tr,Şakir Koç,10,conversation,0,0.00,0.00,10,0,0,...,0.00,10.0,10,turkish,48.1,"odysseus, thaka, adasında, adamları, tulumu",0,0,0,0
42,ssilistre/carnegie-dost-kazanma-tr,Semih Silistre,1001,conversation,0,0.00,0.30,1001,0,154,...,0.70,998.0,1001,turkish,14.9,"carnegie, eleştiri, lincoln, sözü, neden",0,0,0,0
43,ssilistre/semih-silistre-ai-identity,Semih Silistre,382,conversation,0,0.00,0.79,382,0,43,...,0.79,379.0,382,turkish,23.7,"sana, bana, seni, miyim, tanıt",0,0,0,0
44,yoitsmeyusuf/felsefe_finetune,Muhammet Yusuf Kaydın,529,conversation,0,76.56,0.00,0,0,21,...,0.00,529.0,529,turkish,32.1,"kimdir, felsefesi, jean, karl, michel",0,0,58,0

## Sonuçlar

### Portföy toplamları yeniden hesaplanıyor

Bu hücre temel toplamları doğrudan profil dosyasından üretir ve
notebook oluşturulurken gözlenen sabit değerlerle karşılaştırır.

In [4]:
portfolio = pd.Series({
    "dataset_count": len(summary),
    "total_rows": int(summary["rows"].sum()),
    "conversation_rows": int(summary.loc[summary["shape"] == "conversation", "rows"].sum()),
    "instruction_pair_rows": int(summary.loc[summary["shape"] == "instruction_pair", "rows"].sum()),
    "catalog_rows": int(summary.loc[summary["shape"] == "catalog", "rows"].sum()),
    "tabular_rows": int(summary.loc[summary["shape"] == "tabular", "rows"].sum()),
    "thinking_records": int(summary["thinking"].sum()),
    "string_null_fields": int(summary["string_nulls"].sum()),
    "time_sensitive_matches": int(summary["time_sensitive_matches"].sum()),
}, name="value")
assert portfolio["dataset_count"] == 45
assert portfolio["total_rows"] == 87831
portfolio.to_frame()

                        value
dataset_count              45
total_rows              87831
conversation_rows       87228
instruction_pair_rows       0
catalog_rows              103
tabular_rows              500
thinking_records        67470
string_null_fields        462
time_sensitive_matches   3853

### Tekrar yoğunluğu veri setine göre değişiyor

Aşağıdaki tablo üç ölçümü birlikte gösterir. İlk ikisi yalnız büyük
harf ve noktalama farklarını yok sayan tam eşleşmedir.
`near_dup_answers_%` ise bir cevabın daha önceki bir cevapla en az
%85 token örtüşmesi taşıdığı satırları sayar; yeniden yazılmış
kopyaları yakalar. `distinct_answers` sütunu veri setinin gerçekte
kaç farklı cevap içerdiğini verir.

In [5]:
summary.loc[
    summary["shape"].isin(["conversation", "instruction_pair"]),
    ["dataset", "rows", "distinct_answers", "prompt_duplicates_%",
     "answer_duplicates_%", "near_dup_answers_%"],
].sort_values(
    ["answer_duplicates_%", "near_dup_answers_%"], ascending=False
)

,dataset,rows,distinct_answers,prompt_duplicates_%,answer_duplicates_%,near_dup_answers_%
19,enes1863/bilisim-hukuku-domain-dataset,1000,20.0,0.00,98.00,98.00
17,berkcangumusisik/voleykoc-identity-tr,182,26.0,0.00,85.71,85.71
20,enesozdemr/benim_ilk_datasetim,113,17.0,0.00,84.96,84.96
21,erhanalsr/langusta-identity,100,20.0,0.00,80.00,76.00
11,YusufSimsek/turkce-atasozleri-dataset,1398,446.0,0.21,68.10,67.95
35,samliumay/umay_samli_identification_dataset,219,73.0,0.00,66.67,66.67
40,sk75/sahin_identity,77,27.0,0.00,64.94,64.94
29,meldakahramann/animasyon-domain-dataset,1020,420.0,0.00,58.82,61.86
38,sedayzc/turkish-electronics-product-comparison...,11858,5662.0,41.37,52.25,55.96
13,aliFurkan123/identity,30,21.0,0.00,36.36,46.67
16,berkcangumusisik/voleykoc-antrenorluk-tr,166,125.0,0.00,24.70,25.90
32,nyzmemre/biyoloji-terimleri-turkce-sa,1093,857.0,0.18,21.59,22.32
6,SalihHub/trendyol-marangoz-urun-asistan-qa,1211,1028.0,1.32,15.11,9.41
2,Egertekin/marvel-domain-dataset,177,153.0,75.71,13.56,13.56
28,haticenurcakr/turkish-classic-books-qa,220,216.0,0.00,1.82,1.82
31,nursimakgul/meb-soru-uretme,20874,20609.0,86.63,1.27,2.68
26,gorkemergune/ayarlicazhocam_finetune,429,425.0,10.72,0.93,2.10
43,ssilistre/semih-silistre-ai-identity,382,379.0,0.00,0.79,0.79
24,filiz-yalcin/turkish-figure-skating-qa,526,522.0,1.90,0.76,1.90
39,senemde/saglik-qa-tr,553,550.0,0.00,0.54,1.08
3,Endezyar/siyer_datasets,509,507.0,0.98,0.39,0.39
23,filiz-yalcin/identity-finetune,1600,1593.0,2.62,0.31,0.63
42,ssilistre/carnegie-dost-kazanma-tr,1001,998.0,0.00,0.30,0.70
9,Uunan/turkish-cuisine-qa,34244,34227.0,0.01,0.05,1.46
0,Aysenur44/namaz-vakti-dua-asistan-tr,60,60.0,0.00,0.00,6.67
12,aliFurkan123/cultural-questions-dataset,500,500.0,0.00,0.00,0.40
15,berkbirkan/turkish-x-engagement-replies,1000,1000.0,70.10,0.00,0.10
1,Aysenur44/namaz-vakti-identity-tr,4,4.0,0.00,0.00,0.00
4,Erenyanic/seasoned-advice-dataset,1000,1000.0,0.00,0.00,0.00
5,Mer1Alii/TR-ECommerce-CustomerSupport-Instruct...,186,186.0,0.00,0.00,0.00
7,Talayhan/skatepal_dataset,299,299.0,0.00,0.00,0.00
8,Toivo0/Turkce-istatistik-reasoning,400,400.0,0.00,0.00,0.00
10,YusufSimsek/llm-kisisellestirme,46,46.0,0.00,0.00,0.00
14,berkbirkan/turkish-x-engagement-quotes,1000,1000.0,67.70,0.00,0.00
18,cihatyldz/lojistik-soru-cevap,139,139.0,0.00,0.00,0.00
22,erhanalsr/langusta-kpss-reasoning,21,21.0,0.00,0.00,0.00
25,gmz1234/stackoverflow_ai,1000,1000.0,0.00,0.00,0.00
30,namruni/meb-ogretmen-soru-cevap,450,450.0,0.00,0.00,0.00
33,sadecebirisii/turkish-llm-authority-bypass-saf...,29,29.0,0.00,0.00,0.00
34,samliumay/turkish_cyber_security_controls_dataset,800,800.0,0.00,0.00,0.00
36,seali/turkce-saglik-qa,773,773.0,0.13,0.00,0.00
41,srhskrkc/odysseia-destani-tr,10,10.0,0.00,0.00,0.00
44,yoitsmeyusuf/felsefe_finetune,529,529.0,76.56,0.00,0.00

### Satır sayısı ile benzersiz içerik arasındaki fark

Satır sayısı bir kapasite göstergesidir, içerik hacmi değildir.
Aşağıdaki tablo aradaki farkın en büyük olduğu veri setlerini
sıralar; `distinct_answers` sütunu satır sayısının ne kadarının
gerçekten farklı cevaba karşılık geldiğini gösterir.

In [6]:
gap = summary.loc[summary["distinct_answers"].notna()].copy()
gap["answer_gap"] = gap["rows"] - gap["distinct_answers"]
gap.loc[gap["answer_gap"] > 0,
        ["dataset", "rows", "distinct_rows", "distinct_answers", "answer_gap"]
       ].sort_values("answer_gap", ascending=False).head(12)

,dataset,rows,distinct_rows,distinct_answers,answer_gap
38,sedayzc/turkish-electronics-product-comparison...,11858,7007,5662.0,6196.0
19,enes1863/bilisim-hukuku-domain-dataset,1000,1000,20.0,980.0
11,YusufSimsek/turkce-atasozleri-dataset,1398,1398,446.0,952.0
29,meldakahramann/animasyon-domain-dataset,1020,1020,420.0,600.0
31,nursimakgul/meb-soru-uretme,20874,20696,20609.0,265.0
32,nyzmemre/biyoloji-terimleri-turkce-sa,1093,1093,857.0,236.0
6,SalihHub/trendyol-marangoz-urun-asistan-qa,1211,1211,1028.0,183.0
17,berkcangumusisik/voleykoc-identity-tr,182,182,26.0,156.0
35,samliumay/umay_samli_identification_dataset,219,219,73.0,146.0
20,enesozdemr/benim_ilk_datasetim,113,113,17.0,96.0
21,erhanalsr/langusta-identity,100,100,20.0,80.0
40,sk75/sahin_identity,77,77,27.0,50.0

### Veri setleri ne hakkında

Terimler koleksiyonun geri kalanına göre ağırlıklandırılmıştır, yani
sık geçeni değil ayırt edeni gösterir. Yoğunlaşma, en sık yirmi kökün
tüm konu token'ları içindeki payıdır: yüksek değer dar bir söz varlığı
demektir.

In [7]:
summary[["dataset", "rows", "topic_concentration_%", "distinctive_terms"]].sort_values(
    "topic_concentration_%", ascending=False
).head(15)

,dataset,rows,topic_concentration_%,distinctive_terms
1,Aysenur44/namaz-vakti-identity-tr,4,100.0,"yararsın, adın, kimsin, seni, geliştirdi"
20,enesozdemr/benim_ilk_datasetim,113,96.3,"kokulandırılır, petrol, boru, hattı, doğal"
2,Egertekin/marvel-domain-dataset,177,80.6,"örümcek, spider, adam, detaylı, marvel"
13,aliFurkan123/identity,30,75.5,"furkan, trained, tuned, goal, fine"
31,nursimakgul/meb-soru-uretme,20874,73.5,"üret, çoktan, sınıf, seçmeli, orta"
28,haticenurcakr/turkish-classic-books-qa,220,62.8,"eserinin, yayımlanmıştır, edebiyatında, yazarı..."
0,Aysenur44/namaz-vakti-dua-asistan-tr,60,58.9,"namazı, hocam, detaylı, kılınabilir, vakti"
21,erhanalsr/langusta-identity,100,56.3,"yanıtla, cümleyle, açıkça, soruyu, cevapla"
10,YusufSimsek/llm-kisisellestirme,46,53.5,"yusuf, birisi, ilgileniyor, senden, projeleri"
12,aliFurkan123/cultural-questions-dataset,500,52.3,"katının, başkenti, soracağım, kafadan, arkadaşlar"
36,seali/turkce-saglik-qa,773,48.9,"diyabetli, ergenlerde, bilmem, obezite, konusunda"
16,berkcangumusisik/voleykoc-antrenorluk-tr,166,48.6,"voleybol, takımı, kadın, devamı, sormamı"
41,srhskrkc/odysseia-destani-tr,10,48.1,"odysseus, thaka, adasında, adamları, tulumu"
17,berkcangumusisik/voleykoc-identity-tr,182,46.8,"pardon, soracağım, sorry, selam, curious"
24,filiz-yalcin/turkish-figure-skating-qa,526,44.8,"pateninde, artistik, yarışmalarında, atlayış, ..."

### Aynı alanı kapsayan veri setleri

Söz varlığı benzerliği anlam benzerliği değildir; iki İngilizce veri
seti yalnız dil ortaklığı yüzünden yüksek skor alabilir. Her çift
yorumlanmadan önce okunmalıdır.

In [8]:
topics = json.loads(
    (PROJECT_DIR / "outputs" / "topic_overlap.json").read_text(encoding="utf-8")
)["pairs"]
pd.DataFrame(topics).head(12)

,left,right,cosine,shared_terms
0,seali/turkce-saglik-qa,senemde/saglik-qa-tr,0.5680,"[diyabetli, hastalığı, obezite, öneriler, teda..."
1,Erenyanic/seasoned-advice-dataset,gmz1234/stackoverflow_ai,0.3013,"[some, different, like, more, then, other]"
2,Mer1Alii/TR-ECommerce-CustomerSupport-Instruct...,sedayzc/trendyol-electronics-products-features...,0.2700,"[kargo, satıcı, ürün, geldi, sipariş, aldım]"
3,Mer1Alii/TR-ECommerce-CustomerSupport-Instruct...,SalihHub/trendyol-marangoz-urun-asistan-qa,0.2241,"[merhaba, kargo, acaba, ürün, göndermiş, istiy..."
4,Aysenur44/namaz-vakti-identity-tr,ssilistre/semih-silistre-ai-identity,0.2237,"[seni, adın, kimsin, geliştirdi]"
5,Aysenur44/namaz-vakti-identity-tr,berkcangumusisik/voleykoc-identity-tr,0.2226,"[yararsın, adın, kimsin, seni, geliştirdi]"
6,enes1863/bilisim-hukuku-domain-dataset,samliumay/turkish_cyber_security_controls_dataset,0.2103,"[veri, kişisel, bulut, gizlilik, hizmeti, kuru..."
7,berkbirkan/turkish-x-engagement-quotes,berkbirkan/turkish-x-engagement-replies,0.2055,"[aşağıdaki, gönderisini, kısa, alıntılarken, y..."
8,filiz-yalcin/identity-finetune,gmz1234/stackoverflow_ai,0.1998,"[function, some, other, model, more, different]"
9,SalihHub/trendyol-marangoz-urun-asistan-qa,namruni/meb-ogretmen-soru-cevap,0.1891,"[merhaba, acaba, istiyorum, teşekkürler, yapab..."
10,gmz1234/stackoverflow_ai,gorkemergune/ayarlicazhocam_finetune,0.1866,"[learning, neural, network, different, project..."
11,berkbirkan/turkish-x-engagement-replies,erhanalsr/langusta-kpss-reasoning,0.1856,"[aşağıdaki, gönderisine, devleti, ahmet, sanat..."

### Dil sinyali

Türkçeye özgü harflerin tüm harflere oranı ve durak sözcük sayımları
birlikte kaba bir dil sinyali üretir. Bu bir sınıflandırıcı değildir;
yalnız kapsam dışı kalan veri setlerini görünür kılar.

In [9]:
summary.groupby("language_signal")["dataset"].agg(["count", list])

                 count                                               list
language_signal
english              2  [aliFurkan123/identity, gmz1234/stackoverflow_ai]
turkish             43  [Aysenur44/namaz-vakti-dua-asistan-tr, Aysenur...

### Yanıt uzunluğu görev biçimini etkiliyor

Medyan ve p95 kelime sayıları bağlam bütçesi, örnek ağırlığı ve hedef
yanıt biçimi için kullanılır; tek başına içerik doğruluğu göstermez.

In [10]:
summary.loc[
    summary["answer_words_median"].notna(),
    ["dataset", "answer_words_median", "answer_words_p95"],
].sort_values("answer_words_p95", ascending=False)

,dataset,answer_words_median,answer_words_p95
25,gmz1234/stackoverflow_ai,237.0,763.20
23,filiz-yalcin/identity-finetune,245.0,552.10
4,Erenyanic/seasoned-advice-dataset,121.0,366.10
44,yoitsmeyusuf/felsefe_finetune,35.0,353.60
36,seali/turkce-saglik-qa,151.0,330.40
38,sedayzc/turkish-electronics-product-comparison...,108.0,328.00
22,erhanalsr/langusta-kpss-reasoning,200.0,310.00
8,Toivo0/Turkce-istatistik-reasoning,219.5,278.00
33,sadecebirisii/turkish-llm-authority-bypass-saf...,218.0,270.60
16,berkcangumusisik/voleykoc-antrenorluk-tr,63.0,239.00
24,filiz-yalcin/turkish-figure-skating-qa,88.0,234.25
29,meldakahramann/animasyon-domain-dataset,24.5,225.10
42,ssilistre/carnegie-dost-kazanma-tr,141.0,224.00
2,Egertekin/marvel-domain-dataset,56.0,153.40
31,nursimakgul/meb-soru-uretme,58.0,138.00
26,gorkemergune/ayarlicazhocam_finetune,81.0,132.80
5,Mer1Alii/TR-ECommerce-CustomerSupport-Instruct...,87.0,119.00
30,namruni/meb-ogretmen-soru-cevap,81.0,114.55
34,samliumay/turkish_cyber_security_controls_dataset,69.0,112.00
43,ssilistre/semih-silistre-ai-identity,51.0,96.00
7,Talayhan/skatepal_dataset,63.0,89.00
9,Uunan/turkish-cuisine-qa,10.0,78.00
18,cihatyldz/lojistik-soru-cevap,44.0,57.00
41,srhskrkc/odysseia-destani-tr,45.5,53.75
14,berkbirkan/turkish-x-engagement-quotes,15.0,43.05
15,berkbirkan/turkish-x-engagement-replies,15.0,42.00
32,nyzmemre/biyoloji-terimleri-turkce-sa,15.0,41.00
39,senemde/saglik-qa-tr,24.0,40.00
17,berkcangumusisik/voleykoc-identity-tr,28.0,37.00
19,enes1863/bilisim-hukuku-domain-dataset,30.0,34.10
11,YusufSimsek/turkce-atasozleri-dataset,13.0,33.00
35,samliumay/umay_samli_identification_dataset,20.0,31.00
20,enesozdemr/benim_ilk_datasetim,13.0,30.00
10,YusufSimsek/llm-kisisellestirme,19.0,29.75
40,sk75/sahin_identity,11.0,26.00
12,aliFurkan123/cultural-questions-dataset,20.0,24.00
0,Aysenur44/namaz-vakti-dua-asistan-tr,14.5,20.05
3,Endezyar/siyer_datasets,6.0,20.00
6,SalihHub/trendyol-marangoz-urun-asistan-qa,7.0,18.00
13,aliFurkan123/identity,10.0,18.00
28,haticenurcakr/turkish-classic-books-qa,9.5,14.00
21,erhanalsr/langusta-identity,10.0,12.00
1,Aysenur44/namaz-vakti-identity-tr,6.0,10.70

### Şema ve hazırlık sinyalleri ayrı izleniyor

Birebir tekrar, `thinking`, metin biçimindeki `null` ve zaman hassas
eşleşmeleri farklı düzeltme işlemleri gerektirir.

In [11]:
summary[[
    "dataset", "shape", "exact_duplicates", "thinking",
    "string_nulls", "time_sensitive_matches",
]].sort_values(
    ["string_nulls", "thinking", "time_sensitive_matches"],
    ascending=False,
)

,dataset,shape,exact_duplicates,thinking,string_nulls,time_sensitive_matches
40,sk75/sahin_identity,conversation,0,0,462,0
9,Uunan/turkish-cuisine-qa,conversation,0,34244,0,0
31,nursimakgul/meb-soru-uretme,conversation,178,20874,0,560
23,filiz-yalcin/identity-finetune,conversation,0,1600,0,1038
11,YusufSimsek/turkce-atasozleri-dataset,conversation,0,1398,0,0
6,SalihHub/trendyol-marangoz-urun-asistan-qa,conversation,0,1211,0,10
29,meldakahramann/animasyon-domain-dataset,conversation,0,1020,0,0
42,ssilistre/carnegie-dost-kazanma-tr,conversation,0,1001,0,154
4,Erenyanic/seasoned-advice-dataset,conversation,0,1000,0,28
19,enes1863/bilisim-hukuku-domain-dataset,conversation,0,1000,0,0
36,seali/turkce-saglik-qa,conversation,0,773,0,16
24,filiz-yalcin/turkish-figure-skating-qa,conversation,0,526,0,47
12,aliFurkan123/cultural-questions-dataset,conversation,0,500,0,4
30,namruni/meb-ogretmen-soru-cevap,conversation,0,450,0,297
26,gorkemergune/ayarlicazhocam_finetune,conversation,4,429,0,30
8,Toivo0/Turkce-istatistik-reasoning,conversation,0,400,0,12
43,ssilistre/semih-silistre-ai-identity,conversation,0,382,0,43
7,Talayhan/skatepal_dataset,conversation,0,299,0,26
5,Mer1Alii/TR-ECommerce-CustomerSupport-Instruct...,conversation,0,186,0,31
20,enesozdemr/benim_ilk_datasetim,conversation,0,113,0,0
13,aliFurkan123/identity,conversation,0,33,0,0
22,erhanalsr/langusta-kpss-reasoning,conversation,0,21,0,0
41,srhskrkc/odysseia-destani-tr,conversation,0,10,0,0
38,sedayzc/turkish-electronics-product-comparison...,conversation,4851,0,0,699
37,sedayzc/trendyol-electronics-products-features...,tabular,0,0,0,398
14,berkbirkan/turkish-x-engagement-quotes,conversation,0,0,0,141
15,berkbirkan/turkish-x-engagement-replies,conversation,0,0,0,120
16,berkcangumusisik/voleykoc-antrenorluk-tr,conversation,0,0,0,66
35,samliumay/umay_samli_identification_dataset,conversation,0,0,0,62
34,samliumay/turkish_cyber_security_controls_dataset,conversation,0,0,0,38
44,yoitsmeyusuf/felsefe_finetune,conversation,0,0,0,21
33,sadecebirisii/turkish-llm-authority-bypass-saf...,conversation,0,0,0,8
39,senemde/saglik-qa-tr,conversation,0,0,0,2
2,Egertekin/marvel-domain-dataset,conversation,0,0,0,1
18,cihatyldz/lojistik-soru-cevap,conversation,0,0,0,1
0,Aysenur44/namaz-vakti-dua-asistan-tr,conversation,0,0,0,0
1,Aysenur44/namaz-vakti-identity-tr,conversation,0,0,0,0
3,Endezyar/siyer_datasets,conversation,0,0,0,0
10,YusufSimsek/llm-kisisellestirme,conversation,0,0,0,0
17,berkcangumusisik/voleykoc-identity-tr,conversation,0,0,0,0
21,erhanalsr/langusta-identity,conversation,0,0,0,0
25,gmz1234/stackoverflow_ai,conversation,0,0,0,0
27,gururaser/ithaki-bilimkurgu-klasikleri,catalog,0,0,0,0
28,haticenurcakr/turkish-classic-books-qa,conversation,0,0,0,0
32,nyzmemre/biyoloji-terimleri-turkce-sa,conversation,0,0,0,0

### Yapılandırılmış çıktı sözleşmesi ve çelişen hedefler

Bazı veri setleri cevabı JSON olarak tanımlar. `json_like_broken`,
JSON gibi başlayıp ayrıştırılamayan cevapları sayar; sözleşmenin
fiilen ne kadar tutulduğunu gösterir. `conflicting_prompt_families`
ise aynı normalleştirilmiş istemin birden fazla farklı cevapla
eşleştiği aile sayısıdır ve basit tekrardan ayrı bir sorundur.

In [12]:
summary.loc[
    (summary["json_answers"] > 0)
    | (summary["json_like_broken"] > 0)
    | (summary["conflicting_prompt_families"] > 0),
    ["dataset", "rows", "json_answers", "json_like_broken", "conflicting_prompt_families"],
].sort_values("json_like_broken", ascending=False)

,dataset,rows,json_answers,json_like_broken,conflicting_prompt_families
4,Erenyanic/seasoned-advice-dataset,1000,0,24,0
25,gmz1234/stackoverflow_ai,1000,0,2,0
39,senemde/saglik-qa-tr,553,0,1,0
2,Egertekin/marvel-domain-dataset,177,0,0,7
3,Endezyar/siyer_datasets,509,0,0,3
6,SalihHub/trendyol-marangoz-urun-asistan-qa,1211,0,0,12
14,berkbirkan/turkish-x-engagement-quotes,1000,0,0,229
15,berkbirkan/turkish-x-engagement-replies,1000,0,0,212
9,Uunan/turkish-cuisine-qa,34244,0,0,2
11,YusufSimsek/turkce-atasozleri-dataset,1398,0,0,3
24,filiz-yalcin/turkish-figure-skating-qa,526,0,0,8
23,filiz-yalcin/identity-finetune,1600,0,0,33
31,nursimakgul/meb-soru-uretme,20874,17454,0,797
26,gorkemergune/ayarlicazhocam_finetune,429,0,0,34
32,nyzmemre/biyoloji-terimleri-turkce-sa,1093,0,0,2
36,seali/turkce-saglik-qa,773,0,0,1
38,sedayzc/turkish-electronics-product-comparison...,11858,0,0,55
44,yoitsmeyusuf/felsefe_finetune,529,0,0,58

### Veri setleri arası ortak metin aileleri

Ortak istem veya cevaplar birlikte veri hazırlarken aynı şablon
ailesi altında incelenmelidir.

In [13]:
pd.DataFrame(overlaps)

,left,right,shared_user_prompts,shared_assistant_answers,prompt_examples,answer_examples
0,Aysenur44/namaz-vakti-identity-tr,berkcangumusisik/voleykoc-identity-tr,1,0,[ne işe yararsın],[]
1,Aysenur44/namaz-vakti-identity-tr,gorkemergune/ayarlicazhocam_finetune,2,0,"[sen kimsin, seni kim geliştirdi]",[]
2,Aysenur44/namaz-vakti-identity-tr,samliumay/umay_samli_identification_dataset,3,0,"[adın ne, sen kimsin, seni kim geliştirdi]",[]
3,Aysenur44/namaz-vakti-identity-tr,sk75/sahin_identity,4,0,"[adın ne, ne işe yararsın, sen kimsin]",[]
4,Aysenur44/namaz-vakti-identity-tr,ssilistre/semih-silistre-ai-identity,3,0,"[adın ne, sen kimsin, seni kim geliştirdi]",[]
5,YusufSimsek/llm-kisisellestirme,erhanalsr/langusta-identity,1,0,[yaratıcın kim],[]
6,YusufSimsek/llm-kisisellestirme,samliumay/umay_samli_identification_dataset,1,0,[yaratıcın kim],[]
7,YusufSimsek/llm-kisisellestirme,sk75/sahin_identity,1,0,[yaratıcın kim],[]
8,YusufSimsek/llm-kisisellestirme,ssilistre/semih-silistre-ai-identity,1,0,[yaratıcın kim],[]
9,aliFurkan123/identity,berkcangumusisik/voleykoc-identity-tr,4,0,"[hi who are you, what is your name, what is yo...",[]
10,aliFurkan123/identity,filiz-yalcin/identity-finetune,1,0,[could you introduce yourself],[]
11,aliFurkan123/identity,gorkemergune/ayarlicazhocam_finetune,1,0,[who are you],[]
12,aliFurkan123/identity,sk75/sahin_identity,4,0,"[what is your name, what is your purpose, what...",[]
13,aliFurkan123/identity,ssilistre/semih-silistre-ai-identity,5,0,"[are you an ai, are you chatgpt, what model ar...",[]
14,berkcangumusisik/voleykoc-identity-tr,erhanalsr/langusta-identity,1,0,[kendini tanıtır mısın],[]
15,berkcangumusisik/voleykoc-identity-tr,gorkemergune/ayarlicazhocam_finetune,1,0,[who are you],[]
16,berkcangumusisik/voleykoc-identity-tr,samliumay/umay_samli_identification_dataset,1,0,[neler yapabilirsin],[]
17,berkcangumusisik/voleykoc-identity-tr,sk75/sahin_identity,8,0,"[görevin ne, ne işe yararsın, neler yapabilirsin]",[]
18,berkcangumusisik/voleykoc-identity-tr,ssilistre/semih-silistre-ai-identity,6,0,"[görevin ne, introduce yourself, nasıl eğitildin]",[]
19,erhanalsr/langusta-identity,samliumay/umay_samli_identification_dataset,2,0,"[temel görevin nedir, yaratıcın kim]",[]
20,erhanalsr/langusta-identity,sk75/sahin_identity,1,0,[yaratıcın kim],[]
21,erhanalsr/langusta-identity,ssilistre/semih-silistre-ai-identity,1,0,[yaratıcın kim],[]
22,filiz-yalcin/identity-finetune,sk75/sahin_identity,2,0,"[what s your designation, what should i call you]",[]
23,filiz-yalcin/identity-finetune,ssilistre/semih-silistre-ai-identity,1,0,[are you a robot],[]
24,gorkemergune/ayarlicazhocam_finetune,samliumay/umay_samli_identification_dataset,2,0,"[sen kimsin, seni kim geliştirdi]",[]
25,gorkemergune/ayarlicazhocam_finetune,sk75/sahin_identity,4,0,"[sen kimsin, seni kim geliştirdi, who are you]",[]
26,gorkemergune/ayarlicazhocam_finetune,ssilistre/semih-silistre-ai-identity,4,0,"[sen kimsin, seni kim geliştirdi, who are you]",[]
27,samliumay/umay_samli_identification_dataset,sk75/sahin_identity,5,0,"[adın ne, neler yapabilirsin, sen kimsin]",[]
28,samliumay/umay_samli_identification_dataset,ssilistre/semih-silistre-ai-identity,4,0,"[adın ne, sen kimsin, seni kim geliştirdi]",[]
29,sk75/sahin_identity,ssilistre/semih-silistre-ai-identity,12,0,"[adın ne, arkanda kim var, do you have feelings]",[]

### İncelenmiş nitel bulgular

Bu tablo yalnız `manual_findings.json` içinde insan tarafından
gözden geçirilmiş bulguları gösterir. Yeni veri setleri bu dosyaya
eklenmeden burada otomatik olarak yorumlanmaz.

In [14]:
finding_rows = []
for dataset_id, detail in manual.get("datasets", {}).items():
    for finding in detail.get("findings", []):
        finding_rows.append({
            "dataset": dataset_id,
            "severity": finding.get("severity"),
            "evidence": finding.get("evidence"),
            "risk": finding.get("risk"),
            "remediation": finding.get("remediation"),
        })
findings = pd.DataFrame(finding_rows)
findings

,dataset,severity,evidence,risk,remediation
0,Uunan/turkish-cuisine-qa,high,Kart 2.714 benzersiz yemekten 34.244 soru-ceva...,Bir yemeğe ait hatalı bir olgu onlarca kayıtta...,"Yemek kimliğine göre kümele, örneklemi dengele..."
1,Uunan/turkish-cuisine-qa,medium,Asistan cevaplarının medyan uzunluğu 10.0 keli...,Thinking alanı doğrudan eğitilirse model gerek...,Yalnız nihai cevabı içeren türev sürüm üret; t...
2,nursimakgul/meb-soru-uretme,high,Dataset Viewer bu depoyu sunamıyor: meb_identi...,Veri seti standart yükleyicilerle açılamıyor; ...,Her satırı messages anahtarlı bir nesneye sar;...
3,nursimakgul/meb-soru-uretme,high,Cevapların 17.454/20.874 tanesi JSON; kalan 3....,Model aynı istem ailesi için bazen JSON bazen ...,Şemayı zorunlu kıl; JSON olmayan kayıtları ayr...
4,nursimakgul/meb-soru-uretme,high,"Normalleştirilmiş istem tekrarı %86,6 (18.084/...",Aynı sınıf/ders/konu isteminin farklı sorular ...,"İsteme zorluk, kazanım kodu ve soru tipi gibi ..."
...,...,...,...,...,...
82,Aysenur44/namaz-vakti-identity-tr,high,"Veri kartı gövdesi yok; kaynak, amaç ve sınırl...",Hedeflenen davranış ve veri kökeni belirsiz.,Tam bir veri kartı ekle.
83,Aysenur44/namaz-vakti-identity-tr,medium,Dört kullanıcı isteminin tamamı diğer kimlik v...,Kimlik setleri birleştirilirse aynı soru çeliş...,Kimlik setlerini birleştirme; tek personayı seç.
84,sedayzc/trendyol-electronics-products-features...,high,"Veri kartı yok. Kazıma tarihi, kapsam ölçütü v...","Fiyat, puan ve yorum sayısı kazıma anına aitti...","Kazıma tarihi, kapsam ve lisans bilgisini içer..."
85,sedayzc/trendyol-electronics-products-features...,medium,Eksik değerler alanlara dağılmış: comment_coun...,Eksik alanlar dönüşüm şablonlarında boş metin ...,Eksik değer politikası tanımla; zorunlu alanla...
86,sedayzc/trendyol-electronics-products-features...,medium,"Sayısal görünen alanlar (fiyat, puan, yorum sa...",Sayısal işlem yapan boru hattı bu alanlarda ha...,Sayısal alanları tiplendirip eksik değerleri g...

## Çıkarımlar

- Her veri seti kullanım amacı, şeması ve kaynak izlenebilirliğiyle
  birlikte değerlendirilmelidir.
- Birebir tekrarın düşük olması, normalleştirilmiş istem veya cevap
  ailelerinin dengeli olduğu anlamına gelmez.
- Zaman hassas içerikler güncel ve doğrulanabilir kaynak katmanına
  bağlanmalıdır.
- Sohbet, düz istem–cevap, katalog ve genel tablo verileri aynı hedef
  şemaya zorlanmadan önce ayrı hazırlık yollarından geçirilmelidir.
- Nitel sonuçlar, satır örnekleri ve kaynak kartı incelenmeden yalnız
  otomatik profil değerlerinden türetilmemelidir.